# Generated by Django 4.1.2 on 2023-01-29 14:04
# flake8: noqa

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
        ('groups', '0002_studygroup_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fields.field'),
        ),
    ]
