# Generated by Django 4.1.2 on 2023-01-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_studygroup_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='count_students',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='studygroup',
            constraint=models.CheckConstraint(check=models.Q(('count_students__lte', 20)), name='students_lte_20'),
        ),
    ]
