# Generated by Django 4.1.2 on 2023-01-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_studygroup_count_students_studygroup_students_lte_20'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='count_students',
            field=models.IntegerField(default=0),
        ),
    ]
