# Generated by Django 4.1.2 on 2023-01-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_studygroup_subjects'),
        ('fields', '0001_initial'),
        ('users', '0002_user_gender_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='fields.field'),
        ),
        migrations.AddField(
            model_name='user',
            name='study_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='groups.studygroup'),
        ),
    ]
