# Generated by Django 4.1.2 on 2023-01-29 20:56
# flake8: noqa

import django.db.models.deletion
from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_studygroup_field'),
        ('users', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='study_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='groups.studygroup', validators=[users.validators.restrict_number]),
        ),
    ]
