# Generated by Django 4.1.2 on 2023-01-29 21:57
# flake8: noqa

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_study_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('M', 'Mentor'), ('S', 'Student'), ('D', 'Director')], max_length=30),
        ),
    ]
